  name: BingoByDLink
  main: org.andorvini.Main
  version: 1.0.0
  api-version: 1.18
  commands:
      controlpanel:
          description: Opens the control panel
          usage: /<command>
      additem:
          description: Adds item into array
          usage: /<command>